# Generated by Django 4.1.5 on 2025-04-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
    ]
