# Generated by Django 4.1.5 on 2025-04-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_employee_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
    ]
